### ISSUE TITLE
Make file issue

### ISSUE THREAD

**Issue by cxDuuuu** [amarra1122/FinalProject#1]
I have an error here when I run "make Project-550---Intro-Preliminary-Analysis_Marra-FINAL.html": 

> make: *** No rule to make target `Project', needed by `Project-550---Intro-Preliminary-Analysis_Marra-FINAL.html'.  Stop.

**Comment by rachelsagers** [comment]
Error when I run make

"0 [main] make (27076) C:\rtools42\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x210351408/0x180350408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL."
